### ISSUE TITLE
Where to put configuration?

### ISSUE THREAD

**Issue by inspire22** [gwenzek/SublimeSetWindowTitle#14]
Sorry I'm not an expert ST user... I tried putting the configuration shown on the github link into my user settings, but it didn't seem to change what setwindow title did...

**Comment by gwenzek** [comment]
I added a command "SetWindowTitle: Settings" to help you configure the plugin.

It opens the default config and the user config side by side.
If the user config is empty you can just copy paste the content of the default one (or just the part you want to change).

It may take 24h before the new version arrives on PackageControl
