### ISSUE TITLE
ST3 Windows crashes when SublimeSetWindowTitle settings are changed

### ISSUE THREAD

**Issue by mwnciau** [gwenzek/SublimeSetWindowTitle#19]
Since the plugin doesn't create a settings file (which was a bit confusing in and of itself), I've created a settings file in Roaming\Sublime Text 3\Packages\User\set_window_title.sublime-settings. This works fine, but if I edit this file while ST3 is running, it will hang and I have to force close it.

ST Version 3.2.2 Build 3211
SSWT version 1.3.7

**Comment by gwenzek** [comment]
> Since the plugin doesn't create a settings file 

You can do this by using the command "SetWindowTitle: settings" in the command palette (Ctrl+p)
It was added in release 1.3.6, so maybe you missed it.

> if I edit this file while ST3 is running

I assume you're on windows. I think it's the same issue than in #15 and should have been fixed by #16. Let us know if the issue persists.
