### ISSUE TITLE
In linux it doesn't work

### ISSUE THREAD

**Issue by angelrove** [gwenzek/SublimeSetWindowTitle#21]
i use Linux Mint.
Im testing xdotool with a bash script and this is not the problem.

**Comment by gwenzek** [comment]
Can you provide more details please ? xdotools implementation was the more robust. 
Is there an error message in the Sublime Text console ? "ctrl+`" to open it

**Comment by angelrove** [comment]
I have installed Sublime as a tarball and everything has worked correctly.

The extension was not working properly when I install Sublime from Linux Mint Software Manager 'mintinstall' I think it has to do with FlatPack.

Thanks.
