### ISSUE TITLE
Recently created file, SetWindowTitle not changing the title

### ISSUE THREAD

**Issue by ppGrande** [gwenzek/SublimeSetWindowTitle#4]
New file (CRTL + N), opens with nice window title, as you start writing ST takes over the control and start writing the window title, (so no nice window title)

it is just a temporary thing, as soon as you switch from tab or window, it cleans and nice title shows again

(from : 
https://github.com/gwenzek/SublimeSetWindowTitle/issues/3
as I see the problem described initially is solved, and therefore CLOSED)

**Comment by gwenzek** [comment]
Thanks for reporting, but I won't be able to do much about it.
The problem is that I don't want to run the plugin every time the file is modified,
and for new files the title would need to be changed on each modification of the first line.

So save your files so they have a name ^^
