### ISSUE TITLE
Files in a workspace, SetWindowTitle not changing the title

### ISSUE THREAD

**Issue by ppGrande** [gwenzek/SublimeSetWindowTitle#5]
Sorry, another BUG

as working with Workspaces in Projects (ST3) SetWindowTitle does not change the titles.
(one project with more than one workspace)

I found where it seems to be the thing.
Line 141 : `project = window.project_file_name`
inside `def get_project(self, view):` (line 135)

this line is used to recover the project file path to calculate the `official_title` to be able to make the replacement, but as working in workspaces the `official_title` contains the workspace name, and not the project name ...

it seems not to be an API equivalent to `project_file_name()` in https://www.sublimetext.com/docs/3/api_reference.html

so I fear the solution will be difficult ...

I have created an issue on 
[github SublimeTextIssues 2142](https://github.com/SublimeTextIssues/Core/issues/2142)
expecting ST team may look into the necessity of providing some API for Workspaces

**Comment by gwenzek** [comment]
Yes the API for workspaces is not perfect. I added a link in the description and subscribed to https://github.com/SublimeTextIssues/Core/issues/826 so I'll know when the API is available.
